# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  claude-code-aarch64-darwin = {
    pname = "claude-code-aarch64-darwin";
    version = "2.1.210";
    src = fetchurl {
      url = "https://github.com/anthropics/claude-code/releases/download/v2.1.210/claude-darwin-arm64.tar.gz";
      sha256 = "sha256-DTDK7vTdaTszHaMeDgJQ5MpsXsgR9YzpYcJEHSfvsaI=";
    };
  };
  claude-code-aarch64-linux = {
    pname = "claude-code-aarch64-linux";
    version = "2.1.210";
    src = fetchurl {
      url = "https://github.com/anthropics/claude-code/releases/download/v2.1.210/claude-linux-arm64-musl.tar.gz";
      sha256 = "sha256-bMNOEx/IUcz17Ln/u379HMxoCG2ifLTdmIUs6Qtohlk=";
    };
  };
  claude-code-x86_64-linux = {
    pname = "claude-code-x86_64-linux";
    version = "2.1.210";
    src = fetchurl {
      url = "https://github.com/anthropics/claude-code/releases/download/v2.1.210/claude-linux-x64-musl.tar.gz";
      sha256 = "sha256-6koKBB42/h17UJeduq8HDtJ75CsBHnFrPtXFKt016WM=";
    };
  };
  cli-proxy-api-aarch64-darwin = {
    pname = "cli-proxy-api-aarch64-darwin";
    version = "7.2.79";
    src = fetchurl {
      url = "https://github.com/router-for-me/CLIProxyAPI/releases/download/v7.2.79/CLIProxyAPI_7.2.79_darwin_aarch64.tar.gz";
      sha256 = "sha256-5vV4amtojyNm0u5NI3N+jcjD2pggXveAgVVLPbelmWU=";
    };
  };
  cli-proxy-api-aarch64-linux = {
    pname = "cli-proxy-api-aarch64-linux";
    version = "7.2.79";
    src = fetchurl {
      url = "https://github.com/router-for-me/CLIProxyAPI/releases/download/v7.2.79/CLIProxyAPI_7.2.79_linux_aarch64.tar.gz";
      sha256 = "sha256-Jrbgg5gst4v42AYM65rZk97FWMPm3Sygfx2ZhlXGZ9o=";
    };
  };
  cli-proxy-api-x86_64-linux = {
    pname = "cli-proxy-api-x86_64-linux";
    version = "7.2.79";
    src = fetchurl {
      url = "https://github.com/router-for-me/CLIProxyAPI/releases/download/v7.2.79/CLIProxyAPI_7.2.79_linux_amd64.tar.gz";
      sha256 = "sha256-BUiNRb0/SYkqYMNvw2X42Yxhd4hK7M3Khibg+xrbTwo=";
    };
  };
  codex-aarch64-darwin = {
    pname = "codex-aarch64-darwin";
    version = "0.144.4";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.144.4/codex-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-d8iWmkgTAvnbHZ6ipsIcCDq64/Go/Ipyddw4MjaZOR4=";
    };
  };
  codex-aarch64-linux = {
    pname = "codex-aarch64-linux";
    version = "0.144.4";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.144.4/codex-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-TQckPvSuZ4a4syHXrqP5vk4dLFl65UB+fBuYczNAgrI=";
    };
  };
  codex-code-mode-host-aarch64-darwin = {
    pname = "codex-code-mode-host-aarch64-darwin";
    version = "0.144.4";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.144.4/codex-code-mode-host-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-o0KbpqbWWkym8ywpLTXw2gZ2UfwPgzPc+kKnw7a119k=";
    };
  };
  codex-code-mode-host-aarch64-linux = {
    pname = "codex-code-mode-host-aarch64-linux";
    version = "0.144.4";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.144.4/codex-code-mode-host-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-y2nctK5lcykENf5Wch8f7VgPlpl9JY81Nv/hjQX6a48=";
    };
  };
  codex-code-mode-host-x86_64-linux = {
    pname = "codex-code-mode-host-x86_64-linux";
    version = "0.144.4";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.144.4/codex-code-mode-host-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-MClBvtb7PIgp3eX+coZO4ERm7sFiPHO0PNRL8vr+gDg=";
    };
  };
  codex-x86_64-linux = {
    pname = "codex-x86_64-linux";
    version = "0.144.4";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.144.4/codex-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-N8mFvp2J6MT0OzqgWUwSE+rCEtMK4rlSIfCP7IB1FdE=";
    };
  };
  llama-cpp-aarch64-darwin = {
    pname = "llama-cpp-aarch64-darwin";
    version = "10034";
    src = fetchurl {
      url = "https://github.com/ggml-org/llama.cpp/releases/download/b10034/llama-b10034-bin-macos-arm64.tar.gz";
      sha256 = "sha256-pXpoVlvWhQnYYLw871v86R0+PEc2DBATLrB4xetM1Ns=";
    };
  };
  mise-aarch64-darwin = {
    pname = "mise-aarch64-darwin";
    version = "2026.7.7";
    src = fetchurl {
      url = "https://github.com/jdx/mise/releases/download/v2026.7.7/mise-v2026.7.7-macos-arm64.tar.gz";
      sha256 = "sha256-30kNwv/1HIK/D2Th/NAmWxRc6A0tFc6ZuV8q3wsf6Cw=";
    };
  };
  pi-aarch64-darwin = {
    pname = "pi-aarch64-darwin";
    version = "0.80.7";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.80.7/pi-darwin-arm64.tar.gz";
      sha256 = "sha256-DxV3HvduzWmwPij+zwxRJZP/biR3rPOeNbwsikBW0eM=";
    };
  };
  pi-aarch64-linux = {
    pname = "pi-aarch64-linux";
    version = "0.80.7";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.80.7/pi-linux-arm64.tar.gz";
      sha256 = "sha256-vYv0mzbaAPr0G5XIMtr1OFIoFsCVBhkckAvmBoaLtTE=";
    };
  };
  pi-x86_64-linux = {
    pname = "pi-x86_64-linux";
    version = "0.80.7";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.80.7/pi-linux-x64.tar.gz";
      sha256 = "sha256-xfWpp3o45o/LCJ3U41Bau2TJjRlZW1WBjJYb53mIlxk=";
    };
  };
  zed-preview-x86_64-linux = {
    pname = "zed-preview-x86_64-linux";
    version = "1.11.3-pre";
    src = fetchurl {
      url = "https://github.com/zed-industries/zed/releases/download/v1.11.3-pre/zed-linux-x86_64.tar.gz";
      sha256 = "sha256-RbAZBNMgfUtkVukGDFnimpnDLVTGMCjK6nVtn5dYz6E=";
    };
  };
}
