# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agentgateway-aarch64-darwin = {
    pname = "agentgateway-aarch64-darwin";
    version = "1.6.0";
    src = fetchurl {
      url = "https://github.com/agentgateway/agentgateway/releases/download/v1.6.0/agentgateway-darwin-arm64";
      sha256 = "sha256-bOvovVcmLtziOmWjdtL1onuXzf72CXQGQu2+deHpxoU=";
    };
  };
  agentgateway-aarch64-linux = {
    pname = "agentgateway-aarch64-linux";
    version = "1.6.0";
    src = fetchurl {
      url = "https://github.com/agentgateway/agentgateway/releases/download/v1.6.0/agentgateway-linux-arm64";
      sha256 = "sha256-tZ7KwxEDuzF9E3f9QrDLJc2aIfjD8dnuFMP/BfP5Gr8=";
    };
  };
  agentgateway-x86_64-linux = {
    pname = "agentgateway-x86_64-linux";
    version = "1.6.0";
    src = fetchurl {
      url = "https://github.com/agentgateway/agentgateway/releases/download/v1.6.0/agentgateway-linux-amd64";
      sha256 = "sha256-SW7SfmqWtVqa18q+XCvnFyUR9Eo8sRPlM9Ir+Tp/B50=";
    };
  };
  buzz-desktop-aarch64-darwin = {
    pname = "buzz-desktop-aarch64-darwin";
    version = "0.5.26";
    src = fetchurl {
      url = "https://github.com/block/buzz/releases/download/desktop-v0.5.26/Buzz_0.5.26_aarch64.dmg";
      sha256 = "sha256-gTD4nGFj6ySmv/H9d9SZkhQiHwGPHLjQwtMZ8WBTdWk=";
    };
  };
  claude-code-aarch64-darwin = {
    pname = "claude-code-aarch64-darwin";
    version = "2.1.288";
    src = fetchurl {
      url = "https://github.com/anthropics/claude-code/releases/download/v2.1.288/claude-darwin-arm64.tar.gz";
      sha256 = "sha256-hmFsG9stNYE0O0G/FnS5NpkddNFLbVzyBRlM19LhBP4=";
    };
  };
  claude-code-aarch64-linux = {
    pname = "claude-code-aarch64-linux";
    version = "2.1.288";
    src = fetchurl {
      url = "https://github.com/anthropics/claude-code/releases/download/v2.1.288/claude-linux-arm64-musl.tar.gz";
      sha256 = "sha256-Md9kYcL4+WhK6w5s08TQQRqtIWg4J+Gr2a2T7GntQYY=";
    };
  };
  claude-code-x86_64-linux = {
    pname = "claude-code-x86_64-linux";
    version = "2.1.288";
    src = fetchurl {
      url = "https://github.com/anthropics/claude-code/releases/download/v2.1.288/claude-linux-x64-musl.tar.gz";
      sha256 = "sha256-iJl5I5vhjUcEfYj0/L89im/q0oGQUSxCwxo0sj5IAPs=";
    };
  };
  cli-proxy-api-aarch64-darwin = {
    pname = "cli-proxy-api-aarch64-darwin";
    version = "8.0.13";
    src = fetchurl {
      url = "https://github.com/router-for-me/CLIProxyAPI/releases/download/v8.0.13/CLIProxyAPI_8.0.13_darwin_aarch64.tar.gz";
      sha256 = "sha256-ZSoZLj44UgJT4zDEoJT6iRZyg3DD8hPxJ9vFbjW+eTg=";
    };
  };
  cli-proxy-api-aarch64-linux = {
    pname = "cli-proxy-api-aarch64-linux";
    version = "8.0.13";
    src = fetchurl {
      url = "https://github.com/router-for-me/CLIProxyAPI/releases/download/v8.0.13/CLIProxyAPI_8.0.13_linux_aarch64.tar.gz";
      sha256 = "sha256-9/+YoSgHXqhDfa3Vioj0KaQB5FKkLvcRkwQTkYX1NE8=";
    };
  };
  cli-proxy-api-x86_64-linux = {
    pname = "cli-proxy-api-x86_64-linux";
    version = "8.0.13";
    src = fetchurl {
      url = "https://github.com/router-for-me/CLIProxyAPI/releases/download/v8.0.13/CLIProxyAPI_8.0.13_linux_amd64.tar.gz";
      sha256 = "sha256-UOz/tH/dgcjFqYJac6epBatmNCM34nTznEJ2uS01M/M=";
    };
  };
  codex-aarch64-darwin = {
    pname = "codex-aarch64-darwin";
    version = "0.160.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-B8PHyjdqj3kRFTQvUxON2jfpfPopuBJdBlLZN4SJS10=";
    };
  };
  codex-aarch64-linux = {
    pname = "codex-aarch64-linux";
    version = "0.160.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-iDYgE5kl9nfloSyVuoeh1/QhOI67eXscEKukKgTt6dc=";
    };
  };
  codex-code-mode-host-aarch64-darwin = {
    pname = "codex-code-mode-host-aarch64-darwin";
    version = "0.160.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-code-mode-host-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-3HD7x26dyuWuPVQkgIyOfC314NtKyCfd1PvjOQFarXU=";
    };
  };
  codex-code-mode-host-aarch64-linux = {
    pname = "codex-code-mode-host-aarch64-linux";
    version = "0.160.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-code-mode-host-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-lAZv3xP/7NL1h3bsXLj8MEAoOmQuPW/yXF2CBIxBA44=";
    };
  };
  codex-code-mode-host-x86_64-linux = {
    pname = "codex-code-mode-host-x86_64-linux";
    version = "0.160.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-code-mode-host-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-rGzWKI8OOfRqM+uhz9N3EWUfFPM9vHPWobgutF4DjKw=";
    };
  };
  codex-x86_64-linux = {
    pname = "codex-x86_64-linux";
    version = "0.160.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-MGhlQX1O56kneFhSkQpSf0Hh4Vmt05CsWuOsy2fUShM=";
    };
  };
  grok-aarch64-darwin = {
    pname = "grok-aarch64-darwin";
    version = "1.0.46";
    src = fetchurl {
      url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-1.0.46-macos-aarch64";
      sha256 = "sha256-6NqjAjZMnDtqVUbVEc+9GrXl1AepsEKC9mBmXqQF+fM=";
    };
  };
  grok-aarch64-linux = {
    pname = "grok-aarch64-linux";
    version = "1.0.46";
    src = fetchurl {
      url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-1.0.46-linux-aarch64";
      sha256 = "sha256-RbCUPnNvAKJJuc8Cryvp4HSdl8Cab1XPzzApoag28j4=";
    };
  };
  grok-x86_64-linux = {
    pname = "grok-x86_64-linux";
    version = "1.0.46";
    src = fetchurl {
      url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-1.0.46-linux-x86_64";
      sha256 = "sha256-QWJqUykjJBQLklVrnUL/VULj3NBK/4Xq+4aJ3UrbRPw=";
    };
  };
  llama-cpp-aarch64-darwin = {
    pname = "llama-cpp-aarch64-darwin";
    version = "11371";
    src = fetchurl {
      url = "https://github.com/ggml-org/llama.cpp/releases/download/b11371/llama-b11371-bin-macos-arm64.tar.gz";
      sha256 = "sha256-ktd0N3WWS/7NV22yokxB/FijSHe9PDb2zPfovXNajEw=";
    };
  };
  mise-aarch64-darwin = {
    pname = "mise-aarch64-darwin";
    version = "2026.10.0";
    src = fetchurl {
      url = "https://github.com/jdx/mise/releases/download/v2026.10.0/mise-v2026.10.0-macos-arm64.tar.gz";
      sha256 = "sha256-5qlm5E+HFAPfkF1QAZym97hGJN3+HVwJX1vD8YcJJZ4=";
    };
  };
  pi-aarch64-darwin = {
    pname = "pi-aarch64-darwin";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v1.0.0/pi-darwin-arm64.tar.gz";
      sha256 = "sha256-lykefS6y19lasfZ9Jt55AjAiAbyHhsEyu7yeU/qFJsw=";
    };
  };
  pi-aarch64-linux = {
    pname = "pi-aarch64-linux";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v1.0.0/pi-linux-arm64.tar.gz";
      sha256 = "sha256-tgs/2oMKQ8HcP17bX8e2gfIqCpMLSM2sE7l1cMYEWBk=";
    };
  };
  pi-x86_64-linux = {
    pname = "pi-x86_64-linux";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v1.0.0/pi-linux-x64.tar.gz";
      sha256 = "sha256-j9VUOlKoidYK1XzL9slp5zx1xSQKrhisQLUGlHpj3Dg=";
    };
  };
  t3-aarch64-linux = {
    pname = "t3-aarch64-linux";
    version = "0.0.45";
    src = fetchurl {
      url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.45/t3-0.0.45-linux-arm64.tar.gz";
      sha256 = "sha256-kTNZEBfn1HdSX9pmGkbMlSj9YqDEImgHnkNf+zW5Wsk=";
    };
  };
  t3-x86_64-linux = {
    pname = "t3-x86_64-linux";
    version = "0.0.45";
    src = fetchurl {
      url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.45/t3-0.0.45-linux-x64.tar.gz";
      sha256 = "sha256-EFBa50vGpDz6sP3gvwag4NaGL3QDBZG+mUpkDUig1r0=";
    };
  };
  vite-plus-aarch64-darwin = {
    pname = "vite-plus-aarch64-darwin";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/voidzero-dev/vite-plus/releases/download/v1.0.0/vp-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-MJ1CVQNIqhVuNKmi626eixxYhhJrFM2aiPQtFYqUSzU=";
    };
  };
  vite-plus-aarch64-linux = {
    pname = "vite-plus-aarch64-linux";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/voidzero-dev/vite-plus/releases/download/v1.0.0/vp-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-EP2GU5EOLgBZCr49Pkuy2282vWrvJLgcTYqcT5SUACM=";
    };
  };
  vite-plus-x86_64-linux = {
    pname = "vite-plus-x86_64-linux";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/voidzero-dev/vite-plus/releases/download/v1.0.0/vp-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-dy4Fc6/H5d+UAccDga6eN0nBUiD+QlJ2UbwZtvUwEHE=";
    };
  };
  zed-preview-x86_64-linux = {
    pname = "zed-preview-x86_64-linux";
    version = "1.23.1-pre";
    src = fetchurl {
      url = "https://github.com/zed-industries/zed/releases/download/v1.23.1-pre/zed-linux-x86_64.tar.gz";
      sha256 = "sha256-RCqNf1bO2fyN8ybIETTSYGt6ZYNwhPVitKKIPtKS0Gw=";
    };
  };
}
